### ISSUE TITLE
Add type attribute as parameter to shortcode

### ISSUE THREAD

**Issue by blarghmatey** [SecondLineThemes/podcast-subscribe-buttons#1]
It would be useful to be able to pass a `button_type` attribute to the shortcode as a way of toggling between inline and modal displays of the buttons. This way it eliminates the need to specify all of the platform URLs twice as separate instances of the button in order to be able to display them inline as part of the body of the page, or in a modal for a sidebar widget.

I am happy to help contribute this feature if there is interest from the maintainers to include and support it.

**Comment by SecondLineThemes** [comment]
Whoops! Totally missed this open issue. 

That seems to make much sense, it would be cool to switch between layouts with the same actual button/link-set. 

We'll look into it and possibly add it into one of the next updates.

**Comment by blarghmatey** [comment]
Not a problem, thank you for getting back to me. I look forward to seeing
this!

**Comment by SecondLineThemes** [comment]
Okay, just released version 1.1.0 and it should be included!
